/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermosRouteImport } from './routes/termos'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SegurancaRouteImport } from './routes/seguranca'
import { Route as ReembolsoRouteImport } from './routes/reembolso'
import { Route as RedefinirSenhaRouteImport } from './routes/redefinir-senha'
import { Route as PrivacidadeRouteImport } from './routes/privacidade'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedOnboardingRouteImport } from './routes/_authenticated/onboarding'
import { Route as AuthenticatedAppRouteImport } from './routes/_authenticated/app'
import { Route as AuthenticatedAppIndexRouteImport } from './routes/_authenticated/app/index'
import { Route as ApiPublicKiwifyRouteImport } from './routes/api/public/kiwify'
import { Route as AuthenticatedAppSosRouteImport } from './routes/_authenticated/app/sos'
import { Route as AuthenticatedAppProgressoRouteImport } from './routes/_authenticated/app/progresso'
import { Route as AuthenticatedAppDiarioRouteImport } from './routes/_authenticated/app/diario'
import { Route as AuthenticatedAppConfiguracoesRouteImport } from './routes/_authenticated/app/configuracoes'

const TermosRoute = TermosRouteImport.update({
  id: '/termos',
  path: '/termos',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SegurancaRoute = SegurancaRouteImport.update({
  id: '/seguranca',
  path: '/seguranca',
  getParentRoute: () => rootRouteImport,
} as any)
const ReembolsoRoute = ReembolsoRouteImport.update({
  id: '/reembolso',
  path: '/reembolso',
  getParentRoute: () => rootRouteImport,
} as any)
const RedefinirSenhaRoute = RedefinirSenhaRouteImport.update({
  id: '/redefinir-senha',
  path: '/redefinir-senha',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacidadeRoute = PrivacidadeRouteImport.update({
  id: '/privacidade',
  path: '/privacidade',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedOnboardingRoute = AuthenticatedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAppRoute = AuthenticatedAppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAppIndexRoute = AuthenticatedAppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const ApiPublicKiwifyRoute = ApiPublicKiwifyRouteImport.update({
  id: '/api/public/kiwify',
  path: '/api/public/kiwify',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAppSosRoute = AuthenticatedAppSosRouteImport.update({
  id: '/sos',
  path: '/sos',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppProgressoRoute =
  AuthenticatedAppProgressoRouteImport.update({
    id: '/progresso',
    path: '/progresso',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppDiarioRoute = AuthenticatedAppDiarioRouteImport.update({
  id: '/diario',
  path: '/diario',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppConfiguracoesRoute =
  AuthenticatedAppConfiguracoesRouteImport.update({
    id: '/configuracoes',
    path: '/configuracoes',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/privacidade': typeof PrivacidadeRoute
  '/redefinir-senha': typeof RedefinirSenhaRoute
  '/reembolso': typeof ReembolsoRoute
  '/seguranca': typeof SegurancaRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/termos': typeof TermosRoute
  '/app': typeof AuthenticatedAppRouteWithChildren
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/app/configuracoes': typeof AuthenticatedAppConfiguracoesRoute
  '/app/diario': typeof AuthenticatedAppDiarioRoute
  '/app/progresso': typeof AuthenticatedAppProgressoRoute
  '/app/sos': typeof AuthenticatedAppSosRoute
  '/api/public/kiwify': typeof ApiPublicKiwifyRoute
  '/app/': typeof AuthenticatedAppIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/privacidade': typeof PrivacidadeRoute
  '/redefinir-senha': typeof RedefinirSenhaRoute
  '/reembolso': typeof ReembolsoRoute
  '/seguranca': typeof SegurancaRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/termos': typeof TermosRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/app/configuracoes': typeof AuthenticatedAppConfiguracoesRoute
  '/app/diario': typeof AuthenticatedAppDiarioRoute
  '/app/progresso': typeof AuthenticatedAppProgressoRoute
  '/app/sos': typeof AuthenticatedAppSosRoute
  '/api/public/kiwify': typeof ApiPublicKiwifyRoute
  '/app': typeof AuthenticatedAppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/privacidade': typeof PrivacidadeRoute
  '/redefinir-senha': typeof RedefinirSenhaRoute
  '/reembolso': typeof ReembolsoRoute
  '/seguranca': typeof SegurancaRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/termos': typeof TermosRoute
  '/_authenticated/app': typeof AuthenticatedAppRouteWithChildren
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRoute
  '/_authenticated/app/configuracoes': typeof AuthenticatedAppConfiguracoesRoute
  '/_authenticated/app/diario': typeof AuthenticatedAppDiarioRoute
  '/_authenticated/app/progresso': typeof AuthenticatedAppProgressoRoute
  '/_authenticated/app/sos': typeof AuthenticatedAppSosRoute
  '/api/public/kiwify': typeof ApiPublicKiwifyRoute
  '/_authenticated/app/': typeof AuthenticatedAppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/privacidade'
    | '/redefinir-senha'
    | '/reembolso'
    | '/seguranca'
    | '/sitemap.xml'
    | '/termos'
    | '/app'
    | '/onboarding'
    | '/app/configuracoes'
    | '/app/diario'
    | '/app/progresso'
    | '/app/sos'
    | '/api/public/kiwify'
    | '/app/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/privacidade'
    | '/redefinir-senha'
    | '/reembolso'
    | '/seguranca'
    | '/sitemap.xml'
    | '/termos'
    | '/onboarding'
    | '/app/configuracoes'
    | '/app/diario'
    | '/app/progresso'
    | '/app/sos'
    | '/api/public/kiwify'
    | '/app'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/privacidade'
    | '/redefinir-senha'
    | '/reembolso'
    | '/seguranca'
    | '/sitemap.xml'
    | '/termos'
    | '/_authenticated/app'
    | '/_authenticated/onboarding'
    | '/_authenticated/app/configuracoes'
    | '/_authenticated/app/diario'
    | '/_authenticated/app/progresso'
    | '/_authenticated/app/sos'
    | '/api/public/kiwify'
    | '/_authenticated/app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  PrivacidadeRoute: typeof PrivacidadeRoute
  RedefinirSenhaRoute: typeof RedefinirSenhaRoute
  ReembolsoRoute: typeof ReembolsoRoute
  SegurancaRoute: typeof SegurancaRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermosRoute: typeof TermosRoute
  ApiPublicKiwifyRoute: typeof ApiPublicKiwifyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/termos': {
      id: '/termos'
      path: '/termos'
      fullPath: '/termos'
      preLoaderRoute: typeof TermosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seguranca': {
      id: '/seguranca'
      path: '/seguranca'
      fullPath: '/seguranca'
      preLoaderRoute: typeof SegurancaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reembolso': {
      id: '/reembolso'
      path: '/reembolso'
      fullPath: '/reembolso'
      preLoaderRoute: typeof ReembolsoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/redefinir-senha': {
      id: '/redefinir-senha'
      path: '/redefinir-senha'
      fullPath: '/redefinir-senha'
      preLoaderRoute: typeof RedefinirSenhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacidade': {
      id: '/privacidade'
      path: '/privacidade'
      fullPath: '/privacidade'
      preLoaderRoute: typeof PrivacidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/app': {
      id: '/_authenticated/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AuthenticatedAppRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/app/': {
      id: '/_authenticated/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AuthenticatedAppIndexRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/api/public/kiwify': {
      id: '/api/public/kiwify'
      path: '/api/public/kiwify'
      fullPath: '/api/public/kiwify'
      preLoaderRoute: typeof ApiPublicKiwifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/app/sos': {
      id: '/_authenticated/app/sos'
      path: '/sos'
      fullPath: '/app/sos'
      preLoaderRoute: typeof AuthenticatedAppSosRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/progresso': {
      id: '/_authenticated/app/progresso'
      path: '/progresso'
      fullPath: '/app/progresso'
      preLoaderRoute: typeof AuthenticatedAppProgressoRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/diario': {
      id: '/_authenticated/app/diario'
      path: '/diario'
      fullPath: '/app/diario'
      preLoaderRoute: typeof AuthenticatedAppDiarioRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/configuracoes': {
      id: '/_authenticated/app/configuracoes'
      path: '/configuracoes'
      fullPath: '/app/configuracoes'
      preLoaderRoute: typeof AuthenticatedAppConfiguracoesRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
  }
}

interface AuthenticatedAppRouteChildren {
  AuthenticatedAppConfiguracoesRoute: typeof AuthenticatedAppConfiguracoesRoute
  AuthenticatedAppDiarioRoute: typeof AuthenticatedAppDiarioRoute
  AuthenticatedAppProgressoRoute: typeof AuthenticatedAppProgressoRoute
  AuthenticatedAppSosRoute: typeof AuthenticatedAppSosRoute
  AuthenticatedAppIndexRoute: typeof AuthenticatedAppIndexRoute
}

const AuthenticatedAppRouteChildren: AuthenticatedAppRouteChildren = {
  AuthenticatedAppConfiguracoesRoute: AuthenticatedAppConfiguracoesRoute,
  AuthenticatedAppDiarioRoute: AuthenticatedAppDiarioRoute,
  AuthenticatedAppProgressoRoute: AuthenticatedAppProgressoRoute,
  AuthenticatedAppSosRoute: AuthenticatedAppSosRoute,
  AuthenticatedAppIndexRoute: AuthenticatedAppIndexRoute,
}

const AuthenticatedAppRouteWithChildren =
  AuthenticatedAppRoute._addFileChildren(AuthenticatedAppRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedAppRoute: typeof AuthenticatedAppRouteWithChildren
  AuthenticatedOnboardingRoute: typeof AuthenticatedOnboardingRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAppRoute: AuthenticatedAppRouteWithChildren,
  AuthenticatedOnboardingRoute: AuthenticatedOnboardingRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  PrivacidadeRoute: PrivacidadeRoute,
  RedefinirSenhaRoute: RedefinirSenhaRoute,
  ReembolsoRoute: ReembolsoRoute,
  SegurancaRoute: SegurancaRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermosRoute: TermosRoute,
  ApiPublicKiwifyRoute: ApiPublicKiwifyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
